### ISSUE TITLE
add scrollspy func

### ISSUE THREAD

**Issue by DimitarChristoff** [rstacruz/backbone-patterns#13]
Just a suggestion but it works well (obviously, styling may be an issue to consider):

http://fragged.org/backbone-patterns/

works through [my mootools port](https://github.com/DimitarChristoff/mootstrap-scrollspy) of the twitter bootstrap scrollspy - can do a proper clone/pull request, if you like though I imagine you could use the original, which is powered by jquery instead. 

just scroll down or use the menu.

**Comment by john-ka-peter** [comment]
Backbone patterns are very useful for developing Single Page Application in Backbone.js

<a href="http://javascripttrainingcourses.com/JS/BackboneJS-Training" title="Backbone.JS Training in Chennai">Backbone.JS Training in Chennai</a>

**Comment by rstacruz** [comment]
hey there, i've recently done a refresh of the backbone-patterns site. it should have some scrollSpy action on there.

http://ricostacruz.com/backbone-patterns

**Comment by john-ka-peter** [comment]
Yes. It is really interesting on the view pattern. You are using underscore.js for templating. Can you please suggest which is best underscore.js or mustache.js?

<a href="http://javascripttrainingcourses.com/JS/BackboneJS-Training" title="Backbone.JS Training in Chennai">Backbone.JS Training in Chennai</a>
